AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  task-backend

  Sample SAM Template for task-backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  TaskFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: task_handler/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
      - x86_64
      Environment:
        Variables:
          PGSQL_HOST: PGSQL_HOST
          PGSQL_USER: PGSQL_USER
          PGSQL_PASSWORD: PGSQL_USER
          PGSQL_DATABASE: PGSQL_DATABASE
      Events:
        GetTasksByUserFunction:
          Type: Api
          Properties:
            Path: /tasks
            Method: get
        AddTaskFunction:
          Type: Api
          Properties:
            Path: /task
            Method: post
        UpdateTaskFunction:
          Type: Api
          Properties:
            Path: /task
            Method: patch
        DeleteTaskFunction:
          Type: Api
          Properties:
            Path: /task
            Method: delete

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  TaskFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt TaskFunction.Arn
  TaskFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt TaskFunctionRole.Arn
